const mongoose = require("mongoose");

const disputeSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: true,
      trim: true,
    },
    description: {
      type: String,
      required: true,
    },
    reporter: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    autoGenerated: {
      type: Boolean,
      default: false,
    },
    transaction: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Transaction",
    },
    status: {
      type: String,
      enum: ["OPEN", "REVIEW", "INVESTIGATION", "RESOLUTION", "CLOSED"],
      default: "OPEN",
    },
    notes: [
      {
        message: { type: String },
        createdAt: { type: Date, default: Date.now },
      }
    ],
    attachments: [
      {
        fileName: String,
        fileUrl: String,
        uploadedAt: { type: Date, default: Date.now },
      }
    ],
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("Dispute", disputeSchema);
