const mongoose = require("mongoose");

const messageSchema = new mongoose.Schema(
  {
    sender: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    senderRole: { type: String, enum: ["FARMER", "MILL_OWNER", "ADMIN"] },
    message: { type: String, required: true, trim: true },
    attachments: [
      {
        fileName: String,
        fileUrl: String,
      },
    ],
  },
  { timestamps: true }
);

const auditLogSchema = new mongoose.Schema({
  action: { type: String, required: true },
  performedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  performedByRole: { type: String },
  note: { type: String, default: "" },
  timestamp: { type: Date, default: Date.now },
});

const disputeSchema = new mongoose.Schema(
  {
    // ── Legacy title (auto-generated) ─────────────────────────────────────────
    title: { type: String, trim: true },

    // ── Core relationship ─────────────────────────────────────────────────────
    transaction: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Transaction",
      required: true,
    },

    raisedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    againstUser: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },

    // ── Classification ────────────────────────────────────────────────────────
    disputeType: {
      type: String,
      enum: ["QUANTITY_MISMATCH", "PAYMENT_ISSUE", "QUALITY_ISSUE", "TRANSPORT_ISSUE", "OTHER"],
      default: "OTHER",
    },

    description: { type: String, required: true },

    // ── Status lifecycle ──────────────────────────────────────────────────────
    status: {
      type: String,
      enum: ["OPEN", "UNDER_REVIEW", "RESOLVED", "REJECTED"],
      default: "OPEN",
    },

    // ── In-dispute thread (replaces external chat model) ─────────────────────
    messages: [messageSchema],

    // ── Resolution ────────────────────────────────────────────────────────────
    resolution: { type: String, default: "" },

    // Admin decision category (safe — no auto-mutations)
    decisionType: {
      type: String,
      enum: ["REFUND_RECOMMENDED", "PARTIAL_ADJUSTMENT", "WARNING_ISSUED", "NO_ACTION", ""],
      default: "",
    },

    resolvedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    resolvedAt: { type: Date },

    // ── Admin investigation notes (internal admin-only) ───────────────────────
    notes: [
      {
        message: { type: String },
        createdAt: { type: Date, default: Date.now },
      },
    ],

    // ── Evidence attachments (on creation) ───────────────────────────────────
    attachments: [
      {
        fileName: String,
        fileUrl: String,
        uploadedAt: { type: Date, default: Date.now },
      },
    ],

    // ── Audit log ─────────────────────────────────────────────────────────────
    auditLog: [auditLogSchema],

    // ── System flag ──────────────────────────────────────────────────────────
    autoGenerated: { type: Boolean, default: false },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Dispute", disputeSchema);
